# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/HotChocolate/Core
    - name: Build
      run: dotnet build src/HotChocolate/Core --no-restore
    - name: Test
      run: dotnet test src/HotChocolate/Core --no-build --verbosity normal
    - name: Test solution [Debug] with code coverage
        working-directory: src/HotChocolate/Core
        run: >
          dotnet test
          --no-restore
          --no-build
          --collect "XPlat Code Coverage"
          --results-directory .coverage
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude=[HotChocolate.StarWars.Tests]*,[HotChocolate.Tests.Utilities]*
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        files: 'src/HotChocolate/Core/.coverage/**/coverage.opencover.xml'
        verbose: true
