name: Release

on:
  push:
    tags:
      - '13.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
          7.x
          8.x
          
    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
    - name: Build Packages
      run: |
        ./build.sh pack --SemVersion ${{ env.VERSION }}

    - name: Push Packages
      run: |
        ./build.cmd publish --skip
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
    
    - name: Get release
      id: get_release
      run: |
        RELEASE_ID=$(gh api repos/your-username/your-repo/releases/tags/${{ env.VERSION }} --jq '.id')
        UPLOAD_URL=$(gh api repos/your-username/your-repo/releases/$RELEASE_ID --jq '.upload_url')
        echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV
        echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      run: |
        for file in ./**/*.nupkg; do
          echo "Uploading $file"
          gh release upload ${{ env.VERSION }} "$file" --repo your-username/your-repo
        done
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
